import { randomUUID } from "crypto";
import db from "../index.js";

/**
 * Cria os formulários padrão para um usuário
 * @param {number} userId - ID do usuário
 */
export async function createDefaultForms(userId) {
  const defaultForms = [
    {
      name: "Anamnese Adulta",
      description: "Formulário de anamnese para coleta de informações do paciente",
      type: "anamnese",
      questions: [
        { question: "Queixa principal?", answer_type: "textarea", required: true, has_comment: false, order: 0 },
        { question: "Sente dor nos dentes ou na boca?", answer_type: "yes_no_unknown", required: false, has_comment: false, order: 1 },
        { question: "Está em tratamento médico atualmente?", answer_type: "yes_no_unknown", required: false, has_comment: true, order: 2 },
        { question: "Está usando algum medicamento contínuo?", answer_type: "yes_no_unknown", required: false, has_comment: true, order: 3 },
        { question: "Possui alguma alergia (medicamentos, alimentos ou anestesia)?", answer_type: "yes_no_unknown", required: false, has_comment: true, order: 4 },
        { question: "Possui hipertensão (pressão alta)?", answer_type: "yes_no_unknown", required: false, has_comment: false, order: 5 },
        { question: "Possui diabetes?", answer_type: "yes_no_unknown", required: false, has_comment: false, order: 6 },
        { question: "Possui alguma doença respiratória (asma, bronquite etc)?", answer_type: "yes_no_unknown", required: false, has_comment: false, order: 7 },
        { question: "Possui doença cardíaca ou histórico de febre reumática/endocardite?", answer_type: "yes_no_unknown", required: false, has_comment: false, order: 8 },
        { question: "Possui doença infectocontagiosa (HIV, hepatite etc)?", answer_type: "yes_no_unknown", required: false, has_comment: true, order: 9 },
        { question: "Possui alguma doença importante não mencionada?", answer_type: "yes_no_unknown", required: false, has_comment: true, order: 10 },
        { question: "Já foi internado ou realizou cirurgia?", answer_type: "yes_no_unknown", required: false, has_comment: true, order: 11 },
        { question: "Já teve reação alérgica à anestesia odontológica?", answer_type: "yes_no_unknown", required: false, has_comment: true, order: 12 },
        { question: "Apresenta sangramento gengival durante a escovação?", answer_type: "yes_no_unknown", required: false, has_comment: false, order: 13 },
        { question: "Seus dentes são sensíveis a frio, quente ou doces?", answer_type: "yes_no_unknown", required: false, has_comment: false, order: 14 },
        { question: "Sente algum dente mole?", answer_type: "yes_no_unknown", required: false, has_comment: false, order: 15 },
        { question: "Range ou aperta os dentes (bruxismo)?", answer_type: "yes_no_unknown", required: false, has_comment: false, order: 16 },
        { question: "Tem dificuldade para abrir a boca ou sente estalos na mandíbula?", answer_type: "yes_no_unknown", required: false, has_comment: false, order: 17 },
        { question: "Já realizou algum tratamento odontológico (canal, cirurgia, gengiva)?", answer_type: "yes_no_unknown", required: false, has_comment: true, order: 18 },
        { question: "Já usou aparelho ortodôntico?", answer_type: "yes_no_unknown", required: false, has_comment: false, order: 19 },
        { question: "Quando foi sua última consulta ao dentista?", answer_type: "text", required: false, has_comment: false, order: 20 },
        { question: "Quantas vezes por dia escova os dentes?", answer_type: "text", required: false, has_comment: false, order: 21 },
        { question: "Usa fio dental regularmente?", answer_type: "yes_no_unknown", required: false, has_comment: false, order: 22 },
        { question: "Usa enxaguante bucal?", answer_type: "yes_no_unknown", required: false, has_comment: false, order: 23 },
        { question: "Consome muitos doces ou bebidas açucaradas?", answer_type: "yes_no_unknown", required: false, has_comment: false, order: 24 },
        { question: "Fuma?", answer_type: "yes_no_unknown", required: false, has_comment: false, order: 25 },
        { question: "Consome bebidas alcoólicas com frequência?", answer_type: "yes_no_unknown", required: false, has_comment: false, order: 26 },
        { question: "Tem hábito de roer unhas ou morder objetos?", answer_type: "yes_no_unknown", required: false, has_comment: false, order: 27 },
        { question: "Está grávida?", answer_type: "yes_no_unknown", required: false, has_comment: false, order: 28 },
        { question: "Está amamentando?", answer_type: "yes_no_unknown", required: false, has_comment: false, order: 29 },
        { question: "Faz uso de anticoncepcional?", answer_type: "yes_no_unknown", required: false, has_comment: false, order: 30 },
        { question: "Informações adicionais", answer_type: "textarea", required: false, has_comment: false, order: 31 },
      ],
    },
    {
      name: "Anamnese Infantil",
      description: "Formulário de anamnese para coleta de informações do paciente",
      type: "anamnese",
      questions: [
        { question: "Queixa principal?", answer_type: "textarea", required: true, has_comment: false, order: 0 },
        { question: "A criança sente dor nos dentes ou na boca?", answer_type: "yes_no_unknown", required: false, has_comment: false, order: 1 },
        { question: "A criança está em tratamento médico atualmente?", answer_type: "yes_no_unknown", required: false, has_comment: true, order: 2 },
        { question: "Está usando algum medicamento contínuo?", answer_type: "yes_no_unknown", required: false, has_comment: true, order: 3 },
        { question: "Possui alguma alergia (medicamentos, alimentos, anestesia etc)?", answer_type: "yes_no_unknown", required: false, has_comment: true, order: 4 },
        { question: "Possui alguma doença sistêmica (diabetes, asma, anemia etc)?", answer_type: "yes_no_unknown", required: false, has_comment: true, order: 5 },
        { question: "Possui doença cardíaca ou histórico de febre reumática/endocardite?", answer_type: "yes_no_unknown", required: false, has_comment: false, order: 6 },
        { question: "Possui doença infectocontagiosa (HIV, hepatite etc)?", answer_type: "yes_no_unknown", required: false, has_comment: true, order: 7 },
        { question: "Já teve hemorragia ou problema de coagulação?", answer_type: "yes_no_unknown", required: false, has_comment: true, order: 8 },
        { question: "Possui alguma outra doença ou síndrome não mencionada?", answer_type: "yes_no_unknown", required: false, has_comment: true, order: 9 },
        { question: "Já foi internado ou realizou cirurgia?", answer_type: "yes_no_unknown", required: false, has_comment: true, order: 10 },
        { question: "Já apresentou reação alérgica à anestesia odontológica?", answer_type: "yes_no_unknown", required: false, has_comment: true, order: 11 },
        { question: "Apresenta sangramento na gengiva durante a escovação?", answer_type: "yes_no_unknown", required: false, has_comment: false, order: 12 },
        { question: "Os dentes são sensíveis a frio, quente ou doces?", answer_type: "yes_no_unknown", required: false, has_comment: false, order: 13 },
        { question: "A criança range os dentes (bruxismo)?", answer_type: "yes_no_unknown", required: false, has_comment: false, order: 14 },
        { question: "Tem dificuldade para abrir a boca?", answer_type: "yes_no_unknown", required: false, has_comment: false, order: 15 },
        { question: "Já realizou algum tratamento odontológico?", answer_type: "yes_no_unknown", required: false, has_comment: true, order: 16 },
        { question: "Quando foi a última consulta ao dentista?", answer_type: "text", required: false, has_comment: false, order: 17 },
        { question: "Quantas vezes por dia escova os dentes?", answer_type: "text", required: false, has_comment: false, order: 18 },
        { question: "Usa creme dental com flúor?", answer_type: "yes_no_unknown", required: false, has_comment: false, order: 19 },
        { question: "Usa fio dental?", answer_type: "yes_no_unknown", required: false, has_comment: false, order: 20 },
        { question: "Consome muitos doces ou balas?", answer_type: "yes_no_unknown", required: false, has_comment: false, order: 21 },
        { question: "Consome refrigerantes ou bebidas açucaradas com frequência?", answer_type: "yes_no_unknown", required: false, has_comment: false, order: 22 },
        { question: "Possui hábito de roer unhas ou morder objetos?", answer_type: "yes_no_unknown", required: false, has_comment: false, order: 23 },
        { question: "O parto foi normal ou cesariana?", answer_type: "text", required: false, has_comment: false, order: 24 },
        { question: "Peso ao nascer?", answer_type: "text", required: false, has_comment: false, order: 25 },
        { question: "Recebeu aleitamento materno?", answer_type: "yes_no_unknown", required: false, has_comment: false, order: 26 },
        { question: "Fez uso de mamadeira ou chupeta?", answer_type: "yes_no_unknown", required: false, has_comment: false, order: 27 },
        { question: "Teve hábito de sucção de dedo ou lábio?", answer_type: "yes_no_unknown", required: false, has_comment: false, order: 28 },
        { question: "Informações adicionais", answer_type: "textarea", required: false, has_comment: false, order: 29 },
      ],
    },
    {
      name: "Anamnese Odontológica",
      description: "Formulário de anamnese para coleta de informações do paciente",
      type: "anamnese",
      questions: [
        { question: "Queixa principal?", answer_type: "textarea", required: true, has_comment: false, order: 0 },
        { question: "Sente dor nos dentes ou na boca?", answer_type: "yes_no_unknown", required: false, has_comment: false, order: 1 },
        { question: "Está em tratamento médico atualmente?", answer_type: "yes_no_unknown", required: false, has_comment: true, order: 2 },
        { question: "Está usando algum medicamento?", answer_type: "yes_no_unknown", required: false, has_comment: true, order: 3 },
        { question: "Possui alguma alergia (medicamentos, alimentos, anestesia)?", answer_type: "yes_no_unknown", required: false, has_comment: true, order: 4 },
        { question: "Possui alguma doença sistêmica (diabetes, hipertensão, asma etc)?", answer_type: "yes_no_unknown", required: false, has_comment: true, order: 5 },
        { question: "Possui doença cardíaca ou histórico de febre reumática/endocardite?", answer_type: "yes_no_unknown", required: false, has_comment: false, order: 6 },
        { question: "Possui doença infectocontagiosa (HIV, hepatite etc)?", answer_type: "yes_no_unknown", required: false, has_comment: true, order: 7 },
        { question: "Possui alguma outra doença ou síndrome importante?", answer_type: "yes_no_unknown", required: false, has_comment: true, order: 8 },
        { question: "Já foi internado ou realizou cirurgia?", answer_type: "yes_no_unknown", required: false, has_comment: true, order: 9 },
        { question: "Já teve reação alérgica a anestesia odontológica?", answer_type: "yes_no_unknown", required: false, has_comment: true, order: 10 },
        { question: "Apresenta sangramento gengival durante a escovação?", answer_type: "yes_no_unknown", required: false, has_comment: false, order: 11 },
        { question: "Seus dentes são sensíveis a frio, quente ou doces?", answer_type: "yes_no_unknown", required: false, has_comment: false, order: 12 },
        { question: "Range ou aperta os dentes (bruxismo)?", answer_type: "yes_no_unknown", required: false, has_comment: false, order: 13 },
        { question: "Tem dificuldade para abrir a boca?", answer_type: "yes_no_unknown", required: false, has_comment: false, order: 14 },
        { question: "Já realizou algum tratamento odontológico?", answer_type: "yes_no_unknown", required: false, has_comment: true, order: 15 },
        { question: "Já usou aparelho ortodôntico anteriormente?", answer_type: "yes_no_unknown", required: false, has_comment: true, order: 16 },
        { question: "Quando foi sua última consulta ao dentista?", answer_type: "text", required: false, has_comment: false, order: 17 },
        { question: "Quantas vezes por dia escova os dentes?", answer_type: "text", required: false, has_comment: false, order: 18 },
        { question: "Usa fio dental regularmente?", answer_type: "yes_no_unknown", required: false, has_comment: false, order: 19 },
        { question: "Usa enxaguante bucal?", answer_type: "yes_no_unknown", required: false, has_comment: false, order: 20 },
        { question: "Consome muitos doces ou balas?", answer_type: "yes_no_unknown", required: false, has_comment: false, order: 21 },
        { question: "Consome refrigerantes ou bebidas açucaradas com frequência?", answer_type: "yes_no_unknown", required: false, has_comment: false, order: 22 },
        { question: "Tem hábito de roer unhas ou morder objetos?", answer_type: "yes_no_unknown", required: false, has_comment: false, order: 23 },
        { question: "Respira pela boca frequentemente?", answer_type: "yes_no_unknown", required: false, has_comment: false, order: 24 },
        { question: "Utilizou chupeta ou mamadeira por longo período?", answer_type: "yes_no_unknown", required: false, has_comment: false, order: 25 },
        { question: "Teve hábito de sucção de dedo ou lábio?", answer_type: "yes_no_unknown", required: false, has_comment: false, order: 26 },
        { question: "Informações adicionais", answer_type: "textarea", required: false, has_comment: false, order: 27 },
      ],
    },
    {
      name: "Anamnese HOF",
      description: "Formulário de anamnese para coleta de informações do paciente",
      type: "anamnese",
      questions: [
        { question: "Queixa principal?", answer_type: "textarea", required: true, has_comment: false, order: 0 },
        { question: "Está em tratamento médico atualmente?", answer_type: "yes_no_unknown", required: false, has_comment: true, order: 1 },
        { question: "Está usando algum medicamento contínuo?", answer_type: "yes_no_unknown", required: false, has_comment: true, order: 2 },
        { question: "Possui alguma alergia (medicamentos, anestesia, alimentos)?", answer_type: "yes_no_unknown", required: false, has_comment: true, order: 3 },
        { question: "Possui hipertensão (pressão alta)?", answer_type: "yes_no_unknown", required: false, has_comment: false, order: 4 },
        { question: "Possui diabetes?", answer_type: "yes_no_unknown", required: false, has_comment: false, order: 5 },
        { question: "Possui alguma doença respiratória (asma, bronquite etc)?", answer_type: "yes_no_unknown", required: false, has_comment: false, order: 6 },
        { question: "Possui alguma alteração sanguínea (anemia, hemorragia etc)?", answer_type: "yes_no_unknown", required: false, has_comment: true, order: 7 },
        { question: "Possui alguma doença cardiovascular?", answer_type: "yes_no_unknown", required: false, has_comment: false, order: 8 },
        { question: "Possui doença hepática ou renal?", answer_type: "yes_no_unknown", required: false, has_comment: false, order: 9 },
        { question: "Possui doença infectocontagiosa (HIV, hepatite etc)?", answer_type: "yes_no_unknown", required: false, has_comment: true, order: 10 },
        { question: "Possui câncer ou já realizou tratamento oncológico?", answer_type: "yes_no_unknown", required: false, has_comment: true, order: 11 },
        { question: "Possui alguma outra doença ou síndrome importante?", answer_type: "yes_no_unknown", required: false, has_comment: true, order: 12 },
        { question: "Já realizou alguma cirurgia importante?", answer_type: "yes_no_unknown", required: false, has_comment: true, order: 13 },
        { question: "Realizou cirurgia bariátrica?", answer_type: "yes_no_unknown", required: false, has_comment: false, order: 14 },
        { question: "Já teve reação alérgica a anestesia?", answer_type: "yes_no_unknown", required: false, has_comment: true, order: 15 },
        { question: "Está grávida?", answer_type: "yes_no_unknown", required: false, has_comment: false, order: 16 },
        { question: "Está amamentando?", answer_type: "yes_no_unknown", required: false, has_comment: false, order: 17 },
        { question: "Faz uso de anticoncepcional?", answer_type: "yes_no_unknown", required: false, has_comment: false, order: 18 },
        { question: "Fuma?", answer_type: "yes_no_unknown", required: false, has_comment: false, order: 19 },
        { question: "Consome bebidas alcoólicas?", answer_type: "yes_no_unknown", required: false, has_comment: false, order: 20 },
        { question: "Possui manchas, acne ou flacidez na pele?", answer_type: "yes_no_unknown", required: false, has_comment: true, order: 21 },
        { question: "Tem muita exposição solar no dia a dia?", answer_type: "yes_no_unknown", required: false, has_comment: false, order: 22 },
        { question: "Usa filtro solar regularmente?", answer_type: "yes_no_unknown", required: false, has_comment: false, order: 23 },
        { question: "Já realizou algum tratamento estético facial ou de pele?", answer_type: "yes_no_unknown", required: false, has_comment: true, order: 24 },
        { question: "Já utilizou preenchedores não reabsorvíveis (PMMA)?", answer_type: "yes_no_unknown", required: false, has_comment: false, order: 25 },
        { question: "Já realizou peeling químico ou uso de ácidos na pele?", answer_type: "yes_no_unknown", required: false, has_comment: false, order: 26 },
        { question: "O que você gostaria de melhorar no seu rosto?", answer_type: "textarea", required: false, has_comment: false, order: 27 },
        { question: "O que você sente quando se olha no espelho?", answer_type: "textarea", required: false, has_comment: false, order: 28 },
        { question: "Informações adicionais", answer_type: "textarea", required: false, has_comment: false, order: 29 },
      ],
    },
  ];

  // Criar cada formulário padrão
  for (const formData of defaultForms) {
    // Gerar UUIDs para cada questão
    const questions = formData.questions.map((q) => ({
      id: randomUUID(),
      question: q.question,
      answer_type: q.answer_type,
      required: q.required,
      has_comment: q.has_comment,
      order: q.order,
    }));

    const formStructure = {
      questions: questions,
    };

    await db("forms").insert({
      user_id: userId,
      name: formData.name,
      description: formData.description,
      type: formData.type,
      form_structure: JSON.stringify(formStructure),
      created_at: db.fn.now(),
      updated_at: db.fn.now(),
    });
  }
}
